# Generated by Django 4.2.2 on 2023-06-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zipcode',
            new_name='postalcode',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='province',
        ),
    ]
